### PR TITLE
Configure ATECC608A driver I2C address and baud using Mbed OS configuration

### PR DESCRIPTION
**Pull request by TaniaMirzin**
The default device type is ATECC508A, slave address 0xC0

### CODE REVIEW

**Comment by TaniaMirzin** [comment]
@Patater Jeaden, please allow write permission, I will reopen this PR with squash of two latest commits via a branch. I can't perform it on the fork.

**Comment by TaniaMirzin** [comment]
@Patater I also can't edit reviews and Assignees fields for the same reason

**Review by jenia81 — DISMISSED** [review]

**Comment by Patater** [comment]
In addition to squashing the last two commits, please drop commit "Adaptation for specific pre-provisioned Atmel dv." from this PR. Looks good to me otherwise.

**Comment by TaniaMirzin** [comment]
@Patater I still can't create a branch, could you please allow me/our team write permissions?

**Comment by Patater** [comment]
I see you have been able to force push to this existing branch and this PR has updated, but it is missing the "Added ATMEL I2C interface default configuration for device type and slave address" commit.

Could you please re-add the squashed I2C configuration commit and push to this same branch again?

Thanks

**Comment by TaniaMirzin** [comment]
@Patater Ok, please approve.

**Comment by Patater** [comment]
This is missing the commit to update the lib file. Could you please add back the commit "Update mbed-cryptoauthlib" if you want that?

The commit "Added ATMEL I2C interface default configuration for device type..." shouldn't update the lib file. Please keep that change in a separate commit as was done before.

**Comment by TaniaMirzin** [comment]
@Patater The change is inside and also sub-comment is there, is it ok?

**Comment by Patater** [comment]
It shouldn't be inside that commit. It's a separate semantic change.

**Comment by TaniaMirzin** [comment]
@Patater Please approve

**Review by Patater — APPROVED** [review]
LGTM

**Comment by Patater** [comment]
Thanks for making the necessary changes. Looks good now.

**Pull request merged**
