### PR TITLE
Update cryptoauthlib to version 20190903

### PR DESCRIPTION
**Pull request by Patater**

### CODE REVIEW

**Comment by TaniaMirzin** [comment]
@Patater Jaeden, can you please add cryptoauthlib/test/* in .mbedignore? as it was in previous  version? I see that test directory includes unity files and mbed-os in our application compiles its own unity too.
I see also that devtype of cfg_ateccx08a_i2c_default in atca_cfgs.c changed from ATECC608A to ATECC508A. Why we need to change this?

**Comment by Patater** [comment]
@TaniaMirzin This repository never had an mbedignore. Any code changes would have been made upstream by Microchip. The rationale of those changes is best asked of Microchip, if it isn't in the git history.

**Comment by AndrzejKurek** [comment]
@TaniaMirzin I believe that you mean this repository: https://github.com/ARMmbed/mbed-cryptoauthlib? You should be able to add a pull request there.

**Comment by TaniaMirzin** [comment]
@Patater @AndrzejKurek @jenia81 Sorry, I was sure that Motti talked with Jaeden about this https://github.com/mottigondabi/mbed-cryptoauthlib/commit/96bbd884d77f669da3d4f53f5e2ae07b01aec6f5. So you mean that we need to ask them directly for these changes by PR?

**Comment by TaniaMirzin** [comment]
@Patater I see this one https://github.com/ARMmbed/mbed-cryptoauthlib/pull/2, it should resolve it. Jaeden I see that you are reviewer of this.

**Comment by Patater** [comment]
> @Patater I see this one [ARMmbed/mbed-cryptoauthlib#2](https://github.com/ARMmbed/mbed-cryptoauthlib/pull/2), it should resolve it. Jaeden I see that you are reviewer of this.

Motti closed that and raised a new PR, which we reviewed and merged. However, he didn't ignore all of the test folder for some reason. See https://github.com/ARMmbed/mbed-cryptoauthlib/pull/3

As currently stands, applications that use the driver must have in their mbedignore something to ingore either Mbed OS's unity files or Cryptoauthlib's unity files. I find this annoying and would welcome a fix to ignore Cryptoauthlib's unity files.

Please raise a PR with your desired changes at https://github.com/ARMmbed/mbed-cryptoauthlib/. I'm happy to review and merge from there.

**Comment by TaniaMirzin** [comment]
Already opened https://github.com/ARMmbed/mbed-cryptoauthlib/pull/5

**Comment by TaniaMirzin** [comment]
@Patater Can you review it please? https://github.com/ARMmbed/mbed-cryptoauthlib/pull/5
For some reason I can not edit "reviewers" option.Maybe I don't have permissions,can you please try edit it or review it? Thank you.

**Review by AndrzejKurek — APPROVED** [review]
Tested on current head of the example repository (https://github.com/ARMmbed/mbed-os-example-atecc608a/commit/279d358f1039ed6ff826ec3d126f036119e5983c) with a manual fix for the mbed-crypto api change, because of the desync between repositories.
Works fine, tests pass.

**Pull request merged**
